export const BRAND_NAME = "Open Mic Productions";
export const BRAND_DOMAIN = "open-mic.co.za";
export const APP_HOST = "dealroom.open-mic.co.za";
export const APP_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://dealroom.open-mic.co.za";
export const SUPPORT_EMAIL = "support@open-mic.co.za";
export const BRAND_LOGO = "/_static/open-mic/omp_logo_b.svg";
export const BRAND_LOGO_PNG = "/_static/open-mic/omp_logo_b.webp";
export const BRAND_LOGO_WHITE = "/_static/open-mic/omp_logo_w.webp";
export const BRAND_BANNER = "/_static/open-mic/omp_banner_cropped.webp";
